using Microsoft.EntityFrameworkCore;

namespace Janus.Seeding
{
    /// <summary>
    /// Provides a method to seed a <see cref="DbContext"/> with data from the <see cref="IEntitySeeder"/> provided.
    /// </summary>
    public interface IDataContextSeeder
    {
        /// <summary>
        /// Seeds the given context with data generated by the provided seeders.
        /// </summary>
        /// <typeparam name="TContext">The DbContext type</typeparam>
        /// <param name="context">The DbContext instance</param>
        /// <param name="seeders">Collection of seeders that will generate data for inserting into the given DbContext instance.</param>
        void SeedDataContext<TContext>(TContext context, IEntitySeeder[] seeders) where TContext : DbContext;
    }
}
